services:
  - type: web
    name: raceteamsoftware
    env: node
    region: oregon
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
    autoDeploy: true
